name: Java CI Direto (Sem Maven/Gradle)

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Baixar o código do repositório
      uses: actions/checkout@v4

    - name: 2. Configurar o Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Versão padrão usada na FIAP atualmente
        distribution: 'temurin'

    - name: 3. Criar pasta para os arquivos compilados
      run: mkdir bin

    - name: 4. Compilar todos os arquivos Java
      run: |
        find src -name "*.java" > sources.txt
        javac -d bin @sources.txt
